const DataMovie = [
  {
    movie_id: "1",
    title_vi: "TRUY TÌM LONG DIÊN HƯƠNG (T16)",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftruy-tien-long-dien-huong-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=fO6X58qWA_s",
    synopsis:
      "Ngay trước thềm lễ hội lớn, bảo vật Long Diên Hương bị đánh cắp, kéo theo hai anh em Tâm - Tuấn cùng nhóm bạn vào hành trình nghẹt thở nhưng cũng đầy hài hước.",
    duration_mins: 103,
    release_date: "2025-11-10",
    genres: ["Hài", "Hành động", "Phiêu lưu"],
    age_rating: "T16",
    language: "Tiếng Việt",
    subtitles: ["Việt", "Anh"],
    director: "Lâm Hạo Dân",
    status: "now",
    cast: [
      { actor_name: "Quang Tuấn", role: "Tâm" },
      { actor_name: "Ma Ran Đô", role: "Tuấn" },
      { actor_name: "Hoàng Tóc Dài", role: "Bạn Tâm" },
      { actor_name: "Nguyên Thảo", role: "Bạn gái Tuấn" },
    ],
    rating: 8.1,
    format: ["2D", "2D Phụ đề"],
    price: 90000,
    tags: ["Hot", "Việt Nam", "Hài"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["09:30", "11:45", "14:00", "16:20", "18:40", "21:00"],
          "2025-11-20": ["10:15", "12:30", "15:00", "17:30", "20:00", "22:20"],
          "2025-11-21": ["09:45", "12:10", "14:30", "16:50", "19:10", "21:30"],
          "2025-11-22": ["10:00", "12:20", "14:40", "17:00", "19:20", "21:40"],
          "2025-11-23": ["09:30", "11:50", "14:10", "16:30", "18:50", "21:10"],
          "2025-11-24": ["10:30", "13:00", "15:20", "17:40", "20:00", "22:15"],
          "2025-11-25": ["09:45", "12:05", "14:25", "16:45", "19:05", "21:25"],
        },
      },
    ],
    reviews: [
      {
        user: "Minh Khang",
        rating: 9,
        date: "2025-11-18",
        comment:
          "Cười bể bụng luôn! Quang Tuấn với Ma Ran Đô quá duyên, cảnh rượt đuổi hài hước mà đã mắt.",
      },
      {
        user: "Hương Baby",
        rating: 8,
        date: "2025-11-17",
        comment:
          "Xem cùng bạn trai mà cười không ngớt. Hành động đẹp, nhạc nền hợp, đáng tiền vé lắm!",
      },
      {
        user: "Long Đen",
        rating: 10,
        date: "2025-11-19",
        comment:
          "10 điểm không nhưng! Phim Việt mà làm hoành tráng thế này thì Hollywood cũng phải dè chừng.",
      },
      {
        user: "Ngọc Trinh 2k3",
        rating: 7,
        date: "2025-11-16",
        comment:
          "Vui vẻ, dễ xem, phù hợp đi nhóm bạn. Có vài đoạn hơi lố tí nhưng vẫn ổn.",
      },
      {
        user: "Bố Già Fan",
        rating: 9,
        date: "2025-11-19",
        comment:
          "Phim Tết sớm mà chất lượng quá, xem xong muốn book thêm vé cho cả nhà.",
      },
      {
        user: "Reviewer 5 sao",
        rating: 9,
        date: "2025-11-20",
        comment:
          "Phim Việt mà cảm giác như xem blockbuster nước ngoài. Đầu tư chỉnh chu thật sự.",
      },
      {
        user: "Cô gái thích phim hài",
        rating: 8,
        date: "2025-11-20",
        comment: "Hài duyên, thoại không bị sượng. Ra rạp đáng đồng tiền.",
      },
    ],
  },

  {
    movie_id: "2",
    title_vi: "NÚI TẾ VONG (T16)",
    title_en: "The Mourning Mountain",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fnui-te-vong.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=th24BWV__n8",
    synopsis:
      "Ở Đài Loan có một câu nói truyền miệng nổi tiếng về khu rừng dưới Núi Ngọc Sơn, rằng: “Nếu chẳng may lạc trong rừng mà thấy bóng người mặc áo mưa màu vàng thì tuyệt đối đừng đi theo.” Gia Minh (Lưu Dĩ Hào đóng), Ngọc Hân (Viên Lễ Lâm đóng) và An Vĩ (Tào Hựu Ninh đóng) là những người bạn thân trong câu lạc bộ leo núi ở trường đại học. Trong một chuyến leo núi, thay vì đi theo lộ trình ban đầu thì cả 3 lại liều lĩnh bước vào khu vực cấm đã được cảnh báo trong rừng và bị lạc đường. Mặc dù đã buộc những dải vải trắng dọc đường làm ký hiệu, nhưng họ vẫn cứ loanh quanh trở về nơi cũ như thể bị mắc kẹt trong một vòng lặp vô tận. Giữa lúc hỗn loạn, một bóng người mặc áo mưa màu vàng xuất hiện mơ hồ trong sương mù dày đặc mang lại hy vọng cho ba người. Không ngờ, những hiện tượng kỳ lạ liên tiếp xảy ra sau đó mới là bị kịch thật sự.",
    duration_mins: 89,
    release_date: "2025-11-14",
    genres: ["Kinh dị", "Tâm lý"],
    age_rating: "T16",
    language: "Tiếng Trung (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Trương Tử Hào",
    status: "now",
    cast: [
      { actor_name: "Tào Hữu Ninh", role: "Nhân vật chính" },
      { actor_name: "Lưu Dĩ Hào", role: "Bạn thân" },
      { actor_name: "Viên Lễ Lâm", role: "Cô gái bí ẩn" },
    ],
    rating: 7.4,
    format: ["2D"],
    price: 85000,
    tags: ["Kinh dị", "Đang hot"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_2",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["17:45", "20:15", "22:30"],
          "2025-11-20": ["15:50", "19:30", "21:45"],
          "2025-11-21": ["20:40", "23:00"],
          "2025-11-22": ["16:30", "20:00", "22:20"],
          "2025-11-23": ["13:00", "17:15", "19:45", "22:10"],
          "2025-11-24": ["15:20", "19:40", "21:50"],
          "2025-11-25": ["14:30", "18:45", "21:00"],
        },
      },
    ],
    reviews: [
      {
        user: "Khán giả sợ ma",
        rating: 8,
        date: "2025-11-18",
        comment:
          "Ám ảnh thật sự! Không dùng jumpscare rẻ tiền mà vẫn rợn người.",
      },
      {
        user: "Phim kinh dị VN",
        rating: 9,
        date: "2025-11-17",
        comment: "Phim kinh dị Đài Loan mà ám hơn cả Thái Lan.",
      },
      {
        user: "Cậu Vàng",
        rating: 7,
        date: "2025-11-19",
        comment: "Cốt truyện chậm nhưng càng về sau càng căng thẳng.",
      },
      {
        user: "Team thích phim rùng rợn",
        rating: 8,
        date: "2025-11-20",
        comment: "Không nhiều cảnh hù nhưng cảm giác bất an xuyên suốt.",
      },
      {
        user: "Fan Đài Loan",
        rating: 9,
        date: "2025-11-20",
        comment: "Không khí u ám, quay đẹp, âm thanh căng thẳng.",
      },
    ],
  },

  {
    movie_id: "3",
    title_vi: "KHÔNG BÔNG TUYẾT NÀO TRONG SẠCH (T16)",
    title_en: "No Snow Is Innocent",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fkhong-bong-tuyet-nao-trong-sach-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=cd2hUUP-PzY",
    synopsis:
      "Ai rồi cũng nói dối… Một câu chuyện tâm lý đầy bất ngờ về sự thật bị che giấu.",
    duration_mins: 108,
    release_date: "2025-11-14",
    genres: ["Hồi hộp", "Tâm lý", "Tội phạm"],
    age_rating: "T16",
    language: "Tiếng Hàn (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Kim Sung-hoon",
    status: "now",
    cast: [
      { actor_name: "Jung Ryeo-won", role: "Nữ chính" },
      { actor_name: "Lee Jung-eun", role: "Mẹ" },
      { actor_name: "Jang Jin-hee", role: "Bạn thân" },
    ],
    rating: 8.5,
    format: ["2D"],
    price: 95000,
    tags: ["Tâm lý", "Hàn Quốc"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_3",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["17:15", "20:45"],
          "2025-11-20": ["11:20", "15:00", "19:30", "22:10"],
          "2025-11-21": ["14:15", "18:00", "21:30"],
          "2025-11-22": ["10:50", "13:20", "17:00", "20:45"],
          "2025-11-23": ["14:50", "18:30", "21:50"],
          "2025-11-24": ["13:00", "16:40", "20:20"],
          "2025-11-25": ["12:00", "15:45", "19:30", "22:15"],
        },
      },
    ],
    reviews: [
      {
        user: "Cinephile Hàn",
        rating: 10,
        date: "2025-11-18",
        comment: "Plot twist liên hoàn! Phút cuối rớt nước mắt luôn.",
      },
      {
        user: "Mít Ướt",
        rating: 9,
        date: "2025-11-17",
        comment: "Diễn xuất của Jung Ryeo-won đỉnh cao.",
      },
      {
        user: "Detective Conan",
        rating: 10,
        date: "2025-11-19",
        comment: "Xem xong phải ngồi lại 10 phút để xử lý cú twist cuối.",
      },
      {
        user: "Phim tâm lý chân ái",
        rating: 10,
        date: "2025-11-20",
        comment:
          "Nội dung sâu sắc, càng xem càng thấy rợn vì tính hiện thực của nó.",
      },
      {
        user: "Fan drama Hàn",
        rating: 9,
        date: "2025-11-20",
        comment: "Phim xem xong không thoát được cảm xúc trong đầu.",
      },
    ],
  },
  {
    movie_id: "4",
    title_vi: "TÌNH NGƯỜI DUYÊN MA 2025 (T18)",
    title_en: "Pee Mak 2025",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftinh-nguoi-duyen-ma-2025.png&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=KDvKu6rf31s",
    synopsis:
      "Lấy cảm hứng từ truyền thuyết dân gian Thái Lan về hồn ma Mae Nak Phra Khanong.",
    duration_mins: 104,
    release_date: "2025-11-07",
    genres: ["Kinh dị", "Hài", "Lãng mạn"],
    age_rating: "T18",
    language: "Tiếng Thái (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Banjong Pisanthanakun",
    status: "now",
    cast: [
      { actor_name: "Mario Maurer", role: "Mak" },
      { actor_name: "Davika Hoorne", role: "Nak" },
    ],
    rating: 8.8,
    format: ["2D"],
    price: 100000,
    tags: ["Thái Lan", "Kinh dị hài", "T18"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_4",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["21:00", "23:15"],
          "2025-11-20": ["20:30", "22:50"],
          "2025-11-21": ["21:30", "23:50"],
          "2025-11-22": ["21:10", "23:59"],
          "2025-11-23": ["21:30", "23:40"],
          "2025-11-24": ["21:50", "23:59"],
          "2025-11-25": ["22:00", "23:59"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Mario",
        rating: 10,
        date: "2025-11-15",
        comment: "Mario đẹp trai vẫn như ngày nào! Bản remake quá xuất sắc!",
      },
      {
        user: "Ma cũng biết yêu",
        rating: 9,
        date: "2025-11-16",
        comment: "Vừa sợ vừa buồn cười vừa thương Nak.",
      },
      {
        user: "Người mê phim Thái",
        rating: 9,
        date: "2025-11-20",
        comment: "Cảnh quay đẹp, chất liệu dân gian làm rất chỉnh chu.",
      },
      {
        user: "Sinh viên mê phim",
        rating: 10,
        date: "2025-11-20",
        comment: "Đi nhóm bạn coi cười banh nóc rạp!!",
      },
    ],
  },

  {
    movie_id: "5",
    title_vi: "PHÁ ĐÁM SINH NHẬT MẸ (T16)",
    title_en: "Mom's Fake Funeral",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F10-2025%2Fpha-dam-sinh-nhat-me-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=KZQ-oT-l328",
    synopsis:
      "Bị giang hồ đe dọa, một người con trai đã làm đám ma giả để lừa tiền bảo hiểm… và mọi chuyện bắt đầu hỗn loạn!",
    duration_mins: 104,
    release_date: "2025-10-31",
    genres: ["Hài", "Gia đình", "Tình cảm"],
    age_rating: "T16",
    language: "Tiếng Việt",
    subtitles: ["Việt", "Anh"],
    director: "Nguyễn Thanh Bình",
    status: "now",
    cast: [
      { actor_name: "Ái Như", role: "Mẹ" },
      { actor_name: "Thành Lộc", role: "Bố" },
      { actor_name: "Hồng Ánh", role: "Chị gái" },
    ],
    rating: 7.9,
    format: ["2D"],
    price: 85000,
    tags: ["Việt Nam", "Hài cảm động"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_5",
    cinemas: [
      {
        cinema_id: "cns_xuanthuy",
        cinema_name: "Cinestar Xuân Thủy",
        showtimes: {
          "2025-11-17": ["10:00", "14:30", "18:00", "20:45"],
        },
      },
    ],
  },
  {
    movie_id: "6",
    title_vi: "TRUY TÌM LONG DIÊN HƯƠNG (T16)",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftruy-tien-long-dien-huong-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=fO6X58qWA_s",
    synopsis:
      "Ngay trước thềm lễ hội lớn, bảo vật Long Diên Hương bị đánh cắp, kéo theo hai anh em Tâm - Tuấn cùng nhóm bạn vào hành trình nghẹt thở nhưng cũng đầy hài hước.",
    duration_mins: 103,
    release_date: "2025-11-10",
    genres: ["Hài", "Hành động", "Phiêu lưu"],
    age_rating: "T16",
    language: "Tiếng Việt",
    subtitles: ["Việt", "Anh"],
    director: "Lâm Hạo Dân",
    status: "soon",
    cast: [
      { actor_name: "Quang Tuấn", role: "Tâm" },
      { actor_name: "Ma Ran Đô", role: "Tuấn" },
      { actor_name: "Hoàng Tóc Dài", role: "Bạn Tâm" },
      { actor_name: "Nguyên Thảo", role: "Bạn gái Tuấn" },
    ],
    rating: 8.1,
    format: ["2D", "2D Phụ đề"],
    price: 90000,
    tags: ["Hot", "Việt Nam", "Hài"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["09:30", "11:45", "14:00", "16:20", "18:40", "21:00"],
          "2025-11-20": ["10:15", "12:30", "15:00", "17:30", "20:00", "22:20"],
          "2025-11-21": ["09:45", "12:10", "14:30", "16:50", "19:10", "21:30"],
          "2025-11-22": ["10:00", "12:20", "14:40", "17:00", "19:20", "21:40"],
          "2025-11-23": ["09:30", "11:50", "14:10", "16:30", "18:50", "21:10"],
          "2025-11-24": ["10:30", "13:00", "15:20", "17:40", "20:00", "22:15"],
          "2025-11-25": ["09:45", "12:05", "14:25", "16:45", "19:05", "21:25"],
        },
      },
    ],
    reviews: [
      {
        user: "Minh Khang",
        rating: 9,
        date: "2025-11-18",
        comment:
          "Cười bể bụng luôn! Quang Tuấn với Ma Ran Đô quá duyên, cảnh rượt đuổi hài hước mà đã mắt.",
      },
      {
        user: "Hương Baby",
        rating: 8,
        date: "2025-11-17",
        comment:
          "Xem cùng bạn trai mà cười không ngớt. Hành động đẹp, nhạc nền hợp, đáng tiền vé lắm!",
      },
      {
        user: "Long Đen",
        rating: 10,
        date: "2025-11-19",
        comment:
          "10 điểm không nhưng! Phim Việt mà làm hoành tráng thế này thì Hollywood cũng phải dè chừng.",
      },
      {
        user: "Ngọc Trinh 2k3",
        rating: 7,
        date: "2025-11-16",
        comment:
          "Vui vẻ, dễ xem, phù hợp đi nhóm bạn. Có vài đoạn hơi lố tí nhưng vẫn ổn.",
      },
      {
        user: "Bố Già Fan",
        rating: 9,
        date: "2025-11-19",
        comment:
          "Phim Tết sớm mà chất lượng quá, xem xong muốn book thêm vé cho cả nhà.",
      },
      {
        user: "Reviewer 5 sao",
        rating: 9,
        date: "2025-11-20",
        comment:
          "Phim Việt mà cảm giác như xem blockbuster nước ngoài. Đầu tư chỉnh chu thật sự.",
      },
      {
        user: "Cô gái thích phim hài",
        rating: 8,
        date: "2025-11-20",
        comment: "Hài duyên, thoại không bị sượng. Ra rạp đáng đồng tiền.",
      },
    ],
  },
  {
    movie_id: "7",
    title_vi: "TRUY TÌM LONG DIÊN HƯƠNG (T16)",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftruy-tien-long-dien-huong-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=fO6X58qWA_s",
    synopsis:
      "Ngay trước thềm lễ hội lớn, bảo vật Long Diên Hương bị đánh cắp, kéo theo hai anh em Tâm - Tuấn cùng nhóm bạn vào hành trình nghẹt thở nhưng cũng đầy hài hước.",
    duration_mins: 103,
    release_date: "2025-11-10",
    genres: ["Hài", "Hành động", "Phiêu lưu"],
    age_rating: "T16",
    language: "Tiếng Việt",
    subtitles: ["Việt", "Anh"],
    director: "Lâm Hạo Dân",
    status: "soon",
    cast: [
      { actor_name: "Quang Tuấn", role: "Tâm" },
      { actor_name: "Ma Ran Đô", role: "Tuấn" },
      { actor_name: "Hoàng Tóc Dài", role: "Bạn Tâm" },
      { actor_name: "Nguyên Thảo", role: "Bạn gái Tuấn" },
    ],
    rating: 8.1,
    format: ["2D", "2D Phụ đề"],
    price: 90000,
    tags: ["Hot", "Việt Nam", "Hài"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["09:30", "11:45", "14:00", "16:20", "18:40", "21:00"],
          "2025-11-20": ["10:15", "12:30", "15:00", "17:30", "20:00", "22:20"],
          "2025-11-21": ["09:45", "12:10", "14:30", "16:50", "19:10", "21:30"],
          "2025-11-22": ["10:00", "12:20", "14:40", "17:00", "19:20", "21:40"],
          "2025-11-23": ["09:30", "11:50", "14:10", "16:30", "18:50", "21:10"],
          "2025-11-24": ["10:30", "13:00", "15:20", "17:40", "20:00", "22:15"],
          "2025-11-25": ["09:45", "12:05", "14:25", "16:45", "19:05", "21:25"],
        },
      },
    ],
    reviews: [
      {
        user: "Minh Khang",
        rating: 9,
        date: "2025-11-18",
        comment:
          "Cười bể bụng luôn! Quang Tuấn với Ma Ran Đô quá duyên, cảnh rượt đuổi hài hước mà đã mắt.",
      },
      {
        user: "Hương Baby",
        rating: 8,
        date: "2025-11-17",
        comment:
          "Xem cùng bạn trai mà cười không ngớt. Hành động đẹp, nhạc nền hợp, đáng tiền vé lắm!",
      },
      {
        user: "Long Đen",
        rating: 10,
        date: "2025-11-19",
        comment:
          "10 điểm không nhưng! Phim Việt mà làm hoành tráng thế này thì Hollywood cũng phải dè chừng.",
      },
      {
        user: "Ngọc Trinh 2k3",
        rating: 7,
        date: "2025-11-16",
        comment:
          "Vui vẻ, dễ xem, phù hợp đi nhóm bạn. Có vài đoạn hơi lố tí nhưng vẫn ổn.",
      },
      {
        user: "Bố Già Fan",
        rating: 9,
        date: "2025-11-19",
        comment:
          "Phim Tết sớm mà chất lượng quá, xem xong muốn book thêm vé cho cả nhà.",
      },
      {
        user: "Reviewer 5 sao",
        rating: 9,
        date: "2025-11-20",
        comment:
          "Phim Việt mà cảm giác như xem blockbuster nước ngoài. Đầu tư chỉnh chu thật sự.",
      },
      {
        user: "Cô gái thích phim hài",
        rating: 8,
        date: "2025-11-20",
        comment: "Hài duyên, thoại không bị sượng. Ra rạp đáng đồng tiền.",
      },
    ],
  },

  {
    movie_id: "8",
    title_vi: "NÚI TẾ VONG (T16)",
    title_en: "The Mourning Mountain",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fnui-te-vong.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=th24BWV__n8",
    synopsis:
      "Ở Đài Loan có một câu nói truyền miệng nổi tiếng về khu rừng dưới Núi Ngọc Sơn…",
    duration_mins: 89,
    release_date: "2025-11-14",
    genres: ["Kinh dị", "Tâm lý"],
    age_rating: "T16",
    language: "Tiếng Trung (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Trương Tử Hào",
    status: "soon",
    cast: [
      { actor_name: "Tào Hữu Ninh", role: "Nhân vật chính" },
      { actor_name: "Lưu Dĩ Hào", role: "Bạn thân" },
      { actor_name: "Viên Lễ Lâm", role: "Cô gái bí ẩn" },
    ],
    rating: 7.4,
    format: ["2D"],
    price: 85000,
    tags: ["Kinh dị", "Đang hot"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_2",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["09:30", "11:45", "14:00", "16:20", "18:40", "21:00"],
          "2025-11-20": ["10:15", "12:30", "15:00", "17:30", "20:00", "22:20"],
          "2025-11-21": ["09:45", "12:10", "14:30", "16:50", "19:10", "21:30"],
          "2025-11-22": ["10:00", "12:20", "14:40", "17:00", "19:20", "21:40"],
          "2025-11-23": ["09:30", "11:50", "14:10", "16:30", "18:50", "21:10"],
          "2025-11-24": ["10:30", "13:00", "15:20", "17:40", "20:00", "22:15"],
          "2025-11-25": ["09:45", "12:05", "14:25", "16:45", "19:05", "21:25"],
        },
      },
    ],
    reviews: [
      {
        user: "Minh Khang",
        rating: 9,
        date: "2025-11-18",
        comment:
          "Cười bể bụng luôn! Quang Tuấn với Ma Ran Đô quá duyên, cảnh rượt đuổi hài hước mà đã mắt.",
      },
      {
        user: "Hương Baby",
        rating: 8,
        date: "2025-11-17",
        comment:
          "Xem cùng bạn trai mà cười không ngớt. Hành động đẹp, nhạc nền hợp, đáng tiền vé lắm!",
      },
      {
        user: "Long Đen",
        rating: 10,
        date: "2025-11-19",
        comment:
          "10 điểm không nhưng! Phim Việt mà làm hoành tráng thế này thì Hollywood cũng phải dè chừng.",
      },
      {
        user: "Ngọc Trinh 2k3",
        rating: 7,
        date: "2025-11-16",
        comment:
          "Vui vẻ, dễ xem, phù hợp đi nhóm bạn. Có vài đoạn hơi lố tí nhưng vẫn ổn.",
      },
      {
        user: "Bố Già Fan",
        rating: 9,
        date: "2025-11-19",
        comment:
          "Phim Tết sớm mà chất lượng quá, xem xong muốn book thêm vé cho cả nhà.",
      },
      {
        user: "Reviewer 5 sao",
        rating: 9,
        date: "2025-11-20",
        comment:
          "Phim Việt mà cảm giác như xem blockbuster nước ngoài. Đầu tư chỉnh chu thật sự.",
      },
      {
        user: "Cô gái thích phim hài",
        rating: 8,
        date: "2025-11-20",
        comment: "Hài duyên, thoại không bị sượng. Ra rạp đáng đồng tiền.",
      },
    ],
  },
  {
    movie_id: "9",
    title_vi: "KHÔNG BÔNG TUYẾT NÀO TRONG SẠCH (T16)",
    title_en: "No Snow Is Innocent",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fkhong-bong-tuyet-nao-trong-sach-poster.jpg&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=cd2hUUP-PzY",
    synopsis:
      "Ai rồi cũng nói dối… Một câu chuyện tâm lý đầy bất ngờ về sự thật bị che giấu.",
    duration_mins: 108,
    release_date: "2025-11-14",
    genres: ["Hồi hộp", "Tâm lý", "Tội phạm"],
    age_rating: "T16",
    language: "Tiếng Hàn (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Kim Sung-hoon",
    status: "soon",
    cast: [
      { actor_name: "Jung Ryeo-won", role: "Nữ chính" },
      { actor_name: "Lee Jung-eun", role: "Mẹ" },
      { actor_name: "Jang Jin-hee", role: "Bạn thân" },
    ],
    rating: 8.5,
    format: ["2D"],
    price: 95000,
    tags: ["Tâm lý", "Hàn Quốc"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_3",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["09:45", "13:30", "17:15", "20:45"],
          "2025-11-20": ["11:20", "15:00", "19:30", "22:10"],
          "2025-11-21": ["10:30", "14:15", "18:00", "21:30"],
          "2025-11-22": ["10:50", "13:20", "17:00", "20:45"],
          "2025-11-23": ["11:10", "14:50", "18:30", "21:50"],
          "2025-11-24": ["13:00", "16:40", "20:20"],
          "2025-11-25": ["12:00", "15:45", "19:30", "22:15"],
        },
      },
    ],
    reviews: [
      {
        user: "Cinephile Hàn",
        rating: 10,
        date: "2025-11-18",
        comment: "Plot twist liên hoàn! Phút cuối rớt nước mắt luôn.",
      },
      {
        user: "Mít Ướt",
        rating: 9,
        date: "2025-11-17",
        comment: "Diễn xuất của Jung Ryeo-won đỉnh cao.",
      },
      {
        user: "Detective Conan",
        rating: 10,
        date: "2025-11-19",
        comment: "Xem xong phải ngồi lại 10 phút để xử lý cú twist cuối.",
      },
      {
        user: "Phim tâm lý chân ái",
        rating: 10,
        date: "2025-11-20",
        comment:
          "Nội dung sâu sắc, càng xem càng thấy rợn vì tính hiện thực của nó.",
      },
      {
        user: "Fan drama Hàn",
        rating: 9,
        date: "2025-11-20",
        comment: "Phim xem xong không thoát được cảm xúc trong đầu.",
      },
    ],
  },

  {
    movie_id: "10",
    title_vi: "TÌNH NGƯỜI DUYÊN MA 2025 (T18)",
    title_en: "Pee Mak 2025",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftinh-nguoi-duyen-ma-2025.png&w=1080&q=75",
    trailer_url: "https://www.youtube.com/watch?v=KDvKu6rf31s",
    synopsis:
      "Lấy cảm hứng từ truyền thuyết dân gian Thái Lan về hồn ma Mae Nak Phra Khanong.",
    duration_mins: 104,
    release_date: "2025-11-07",
    genres: ["Kinh dị", "Hài", "Lãng mạn"],
    age_rating: "T18",
    language: "Tiếng Thái (Phụ đề Việt)",
    subtitles: ["Việt", "Anh"],
    director: "Banjong Pisanthanakun",
    status: "soon",
    cast: [
      { actor_name: "Mario Maurer", role: "Mak" },
      { actor_name: "Davika Hoorne", role: "Nak" },
    ],
    rating: 8.8,
    format: ["2D"],
    price: 100000,
    tags: ["Thái Lan", "Kinh dị hài", "T18"],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_4",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["21:00", "23:15"],
          "2025-11-20": ["20:30", "22:50"],
          "2025-11-21": ["21:30", "23:50"],
          "2025-11-22": ["21:10", "23:59"],
          "2025-11-23": ["21:30", "23:40"],
          "2025-11-24": ["21:50", "23:59"],
          "2025-11-25": ["22:00", "23:59"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Mario",
        rating: 10,
        date: "2025-11-15",
        comment: "Mario đẹp trai vẫn như ngày nào! Bản remake quá xuất sắc!",
      },
      {
        user: "Ma cũng biết yêu",
        rating: 9,
        date: "2025-11-16",
        comment: "Vừa sợ vừa buồn cười vừa thương Nak.",
      },
      {
        user: "Người mê phim Thái",
        rating: 9,
        date: "2025-11-20",
        comment: "Cảnh quay đẹp, chất liệu dân gian làm rất chỉnh chu.",
      },
      {
        user: "Sinh viên mê phim",
        rating: 10,
        date: "2025-11-20",
        comment: "Đi nhóm bạn coi cười banh nóc rạp!!",
      },
    ],
  },
  {
    movie_id: "12",
    title_vi: "MỘ ĐOM ĐÓM ",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fmo-dom-dom.jpg&w=2048&q=75",
    trailer_url: "https://youtu.be/lhlh7JVcTt8?t=6",
    synopsis:
      "Hai anh em Seita và Setsuko mất mẹ sau cuộc thả bom dữ dội của không quân Mỹ. Cả hai phải vật lộn để tồn tại ở Nhật Bản hậu Thế chiến II. Nhưng xã hội khắc nghiệt và chúng vật lộn tìm kiếm thức ăn cũng như thoát khỏi những khó khăn giữa chiến tranh.",
    duration_mins: 89,
    release_date: "2025-11-18",
    genres: ["Hoạt hình"],
    age_rating: "T16",
    language: "Nhật Bản",
    subtitles: ["Việt", "Anh"],
    director: "Takahata Isao",
    status: "now",
    cast: [
      { actor_name: "Quang Tuấn", role: "Tâm" },
      { actor_name: "Ma Ran Đô", role: "Tuấn" },
      { actor_name: "Hoàng Tóc Dài", role: "Bạn Tâm" },
      { actor_name: "Nguyên Thảo", role: "Bạn gái Tuấn" },
    ],
    rating: 9.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Nhật Bản", "Cảm Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["10:30", "15:00", "19:30"],
          "2025-11-20": ["11:40", "16:20", "20:00"],
          "2025-11-21": ["10:00", "14:30", "18:45"],
          "2025-11-22": ["09:30", "13:50", "17:40", "20:10"],
          "2025-11-23": ["10:15", "15:30", "19:00"],
          "2025-11-24": ["11:00", "16:10", "20:30"],
          "2025-11-25": ["10:45", "15:20", "19:45"],
        },
      },
    ],
    reviews: [
      {
        user: "Ghibli Forever",
        rating: 10,
        date: "2025-11-19",
        comment: "Vẫn khóc như lần đầu xem năm 1988. Kiệt tác bất hủ.",
      },
      {
        user: "Học sinh lớp 9",
        rating: 10,
        date: "2025-11-19",
        comment: "Cô giáo cho xem ở trường, cả lớp im lặng khóc.",
      },
      {
        user: "Bố 2 con",
        rating: 10,
        date: "2025-11-18",
        comment: "Đưa con đi xem để hiểu giá trị của hòa bình và tình thân.",
      },
      {
        user: "Fan Studio Ghibli",
        rating: 10,
        date: "2025-11-20",
        comment: "Ai có anh/chị/em xem kiểu gì cũng vỡ tim.",
      },
      {
        user: "Sinh viên năm nhất",
        rating: 9,
        date: "2025-11-20",
        comment: "Phim chiến tranh nhưng đầy chất thơ, cảm xúc dồn dập.",
      },
    ],
  },
  {
    movie_id: "13",
    title_vi: "TRỐN CHẠY TỬ THẦN (T18) ",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftron-chay-tu-than-poster.jpg&w=2048&q=75",
    trailer_url: "https://youtu.be/td2rovvBmSE",
    synopsis:
      "Trong bối cảnh xã hội tương lai gần, Trốn Chạy Tử Thần là chương trình truyền hình ăn khách nhất, một cuộc thi sinh tồn khốc liệt nơi các thí sinh, được gọi là “Runners”, phải trốn chạy suốt 30 ngày khỏi sự truy đuổi của các sát thủ chuyên nghiệp. Mọi bước đi của họ đều được phát sóng công khai cho khán giả theo dõi và phần thưởng tiền mặt sẽ tăng lên sau mỗi ngày sống sót. Vì cần tiền cứu chữa cho cô con gái bệnh nặng, Ben Richards (do Glen Powell thủ vai), một người lao động nghèo, chấp nhận lời mời từ Dan Killian (do Josh Brolin thủ vai), nhà sản xuất chương trình bảnh bao nhưng tàn nhẫn, để tham gia cuộc chơi như một lựa chọn cuối cùng. Tuy nhiên, sự gan lì, nhạy bén và ý chí sinh tồn mãnh liệt của Ben lại khiến anh bất ngờ trở thành nhân vật được khán giả yêu thích nhất và là mối đe dọa với cả hệ thống. Khi lượng người xem tăng vọt, hiểm nguy cũng ngày càng bủa vây. Giờ đây, Ben không chỉ phải đối mặt với toán sát thủ mà còn cả một đất nước đang nghiện cảm giác chứng kiến anh gục ngã.",
    duration_mins: 133,
    release_date: "21/11/2025",
    genres: ["Phiêu Lưu, Khoa Học Viễn Tưởng"],
    age_rating: "T18",
    language: "Mỹ",
    subtitles: ["Việt", "Anh"],
    director: "Edgar Wright",
    status: "soon",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 9,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Mỹ", "Hành Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-21": ["13:00", "16:15", "19:30", "22:45"],
          "2025-11-22": ["10:00", "13:15", "16:30", "19:45", "23:00"],
          "2025-11-23": ["11:00", "14:15", "17:30", "20:45"],
          "2025-11-24": ["12:30", "15:45", "19:00", "22:15"],
          "2025-11-25": ["13:15", "16:30", "19:45", "23:00"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan hành động",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Trailer cháy máy! Hy vọng phim giữ được nhịp và sự kịch tính như bản gốc.",
      },
      {
        user: "Chờ IMAX",
        rating: 0,
        date: "2025-11-20",
        comment: "Đặt vé IMAX ngay khi mở bán!",
      },
    ],
  },
  {
    movie_id: "14",
    title_vi: "QUÁI THÚ VÔ HÌNH: VÙNG ĐẤT CHẾT CHÓC",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Fquai-thu-vo-hinh.jpg&w=2048&q=75",
    trailer_url: "https://youtu.be/gIsCRPnLpYst",
    synopsis:
      "Trong bối cảnh xã hội tương lai gần, Trốn Chạy Tử Thần là chương trình truyền hình ăn khách nhất, một cuộc thi sinh tồn khốc liệt nơi các thí sinh, được gọi là “Runners”, phải trốn chạy suốt 30 ngày khỏi sự truy đuổi của các sát thủ chuyên nghiệp. Mọi bước đi của họ đều được phát sóng công khai cho khán giả theo dõi và phần thưởng tiền mặt sẽ tăng lên sau mỗi ngày sống sót. Vì cần tiền cứu chữa cho cô con gái bệnh nặng, Ben Richards (do Glen Powell thủ vai), một người lao động nghèo, chấp nhận lời mời từ Dan Killian (do Josh Brolin thủ vai), nhà sản xuất chương trình bảnh bao nhưng tàn nhẫn, để tham gia cuộc chơi như một lựa chọn cuối cùng. Tuy nhiên, sự gan lì, nhạy bén và ý chí sinh tồn mãnh liệt của Ben lại khiến anh bất ngờ trở thành nhân vật được khán giả yêu thích nhất và là mối đe dọa với cả hệ thống. Khi lượng người xem tăng vọt, hiểm nguy cũng ngày càng bủa vây. Giờ đây, Ben không chỉ phải đối mặt với toán sát thủ mà còn cả một đất nước đang nghiện cảm giác chứng kiến anh gục ngã.",
    duration_mins: 107,
    release_date: "20/11/2025",
    genres: ["Phiêu Lưu, Hành Động"],
    age_rating: "T16",
    language: "Mỹ",
    subtitles: ["Việt", "Anh"],
    director: "Dan Trachtenberg",
    status: "now",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Mỹ", "Hành Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "15",
    title_vi: "GODZILLA MINUS ONE",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/_/o/_option_1_g-1_full_poster_outline_up.jpg",
    trailer_url: "https://youtu.be/gIsCRPnLpYst",
    synopsis:
      "Năm 1945, khi Thế chiến thứ Hai đang đi đến hồi kết, phi công Nhật Bản Koichi Shikishima bất ngờ chạm trán một quái vật biển đến từ cõi ngoài, mà người dân trên đảo Odo gọi là Godzilla. Bị giày vò bởi nỗi tội lỗi của kẻ sống sót — vì không thể bắn hạ con quái vật bằng súng gắn trên máy bay, và vì đã bỏ lại nhiệm vụ cảm tử của mình — Shikishima tìm được chút niềm an ủi mong manh bên Noriko, một người phụ nữ sống sót sau các đợt không kích Tokyo, và Akiko, một bé gái mồ côi. Năm tháng trôi qua, Shikishima dần mở lòng với Noriko và những người xung quanh. Nhưng bóng ma quá khứ — lần chạm trán năm xưa với Godzilla, nay đã biến đổi và nhiễm phóng xạ — lại một lần nữa trỗi dậy, khi toàn bộ nước Nhật chìm trong tuyệt vọng và kinh hoàng.",
    duration_mins: 126,
    release_date: "22/11/2025",
    genres: ["Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu"],
    age_rating: "T16",
    language: "Nhật Bản",
    subtitles: ["Việt", "Anh"],
    director: " Takashi Yamazaki",
    status: "now",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Nhật Bản", "Hành Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "16",
    title_vi: "TÌNH NGƯỜI DUYÊN MA 2025",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/7/0/700x1000-peemak.jpg",
    trailer_url: "https://youtu.be/TpUvaW2ymeg",
    synopsis:
      "Lấy cảm hứng từ truyền thuyết dân gian Thái Lan về hồn ma Mae Nak, Tình Người Duyên Ma: Nhắm Mak Yêu Luôn kể câu chuyện tình vượt thời gian giữa nàng Nak và chàng Mak. Xuyên không đến 200 năm sau, Nak bất ngờ được vào vai nữ chính trong chính bộ phim về truyền thuyết của mình. Tình cờ thay, vai nam chính lại được thủ bởi Mak - lúc này đã là một nam diễn viên nổi tiếng toàn quốc. Ở đây, Nak phải chinh phục lại trái tim Mak trong vòng 30 ngày mà không được dùng đến ma lực, để có thể ở bên anh trọn đời trọn kiếp.",
    duration_mins: 104,
    release_date: "07/11/2025",
    genres: ["Hài, Kinh Dị, Tình cảm"],
    age_rating: "T13",
    language: "Thái Lan",
    subtitles: ["Việt", "Anh"],
    director: "Choosak Iamsook",
    status: "now",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 9.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Thái Lan", "Hành Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-19": ["21:00", "23:15"],
          "2025-11-20": ["20:30", "22:50"],
          "2025-11-21": ["21:30", "23:50"],
          "2025-11-22": ["21:10", "23:59"],
          "2025-11-23": ["21:30", "23:40"],
          "2025-11-24": ["21:50", "23:59"],
          "2025-11-25": ["22:00", "23:59"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Mario",
        rating: 10,
        date: "2025-11-15",
        comment: "Mario đẹp trai vẫn như ngày nào! Bản remake quá xuất sắc!",
      },
      {
        user: "Ma cũng biết yêu",
        rating: 9,
        date: "2025-11-16",
        comment: "Vừa sợ vừa buồn cười vừa thương Nak.",
      },
      {
        user: "Người mê phim Thái",
        rating: 9,
        date: "2025-11-20",
        comment: "Cảnh quay đẹp, chất liệu dân gian làm rất chỉnh chu.",
      },
      {
        user: "Sinh viên mê phim",
        rating: 10,
        date: "2025-11-20",
        comment: "Đi nhóm bạn coi cười banh nóc rạp!!",
      },
    ],
  },
  {
    movie_id: "17",
    title_vi: "GODZILLA MINUS ONE",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/_/o/_option_1_g-1_full_poster_outline_up.jpg",
    trailer_url: "https://youtu.be/gIsCRPnLpYst",
    synopsis:
      "Năm 1945, khi Thế chiến thứ Hai đang đi đến hồi kết, phi công Nhật Bản Koichi Shikishima bất ngờ chạm trán một quái vật biển đến từ cõi ngoài, mà người dân trên đảo Odo gọi là Godzilla. Bị giày vò bởi nỗi tội lỗi của kẻ sống sót — vì không thể bắn hạ con quái vật bằng súng gắn trên máy bay, và vì đã bỏ lại nhiệm vụ cảm tử của mình — Shikishima tìm được chút niềm an ủi mong manh bên Noriko, một người phụ nữ sống sót sau các đợt không kích Tokyo, và Akiko, một bé gái mồ côi. Năm tháng trôi qua, Shikishima dần mở lòng với Noriko và những người xung quanh. Nhưng bóng ma quá khứ — lần chạm trán năm xưa với Godzilla, nay đã biến đổi và nhiễm phóng xạ — lại một lần nữa trỗi dậy, khi toàn bộ nước Nhật chìm trong tuyệt vọng và kinh hoàng.",
    duration_mins: 126,
    release_date: "17/11/2025",
    genres: ["Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu"],
    age_rating: "T16",
    language: "Nhật Bản",
    subtitles: ["Việt", "Anh"],
    director: " Takashi Yamazaki",
    status: "now",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Nhật Bản", "Hành Động "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "18",
    title_vi: "TAFITI - NÁO LOẠN SA MẠC (P) LT",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F11-2025%2Ftafiti.jpg&w=2048&q=75",
    trailer_url: "https://youtu.be/n9Jv1bEjSgk",
    synopsis:
      "Chú chồn đất Tafiti vốn chỉ mong một cuộc sống yên bình giữa thảo nguyên nhưng cứ bị chú heo rừng hậu đậu, tốt bụng Bristles làm đảo lộn mọi thứ. Khi ông nội không may bị rắn độc cắn, Tafiti buộc phải vượt qua sa mạc khắc nghiệt để tìm bông hoa xanh hiếm có nhằm cứu ông. Chuyến phiêu lưu đầy tiếng cười và thử thách cùng Bristles giúp Tafiti nhận ra rằng điều quý giá nhất trong mọi hành trình không phải là đích đến, mà là những người bạn đồng hành bên cạnh.",
    duration_mins: 80,
    release_date: "21/11/2025",
    genres: ["Hoạt Hình"],
    age_rating: "T13",
    language: "Mỹ",
    subtitles: ["Việt", "Anh"],
    director: " Nian Wels",
    status: "soon",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Mỹ ", "Hoạt Hình "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "19",
    title_vi: "CƯỚI VỢ CHO CHA",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-cvcc.jpg",
    trailer_url: "https://youtu.be/wiQhdvi4QvY",
    synopsis:
      "Ở một xóm nhỏ miền Tây, ông Sáu Sếu sống lủi thủi trong quán cà phê – karaoke, mong con trai Út Tửng từ Sài Gòn về thăm. Khi phát hiện mình mắc trọng bệnh, ông quyết “cưới vợ cho con” để trọn lời hứa với người vợ quá cố. Nhưng kế hoạch ấy đổ vỡ khi ông phát hiện Tửng có một bí mật động trời và che giấu mọi chuyện. Giữa những xung đột, hiểu lầm và nỗ lực hàn gắn, cha con họ dần học cách thấu hiểu, để rồi mỗi người đều tìm thấy hạnh phúc và bình yên trong chính cuộc hôn nhân của mình.",
    duration_mins: 112,
    release_date: "21/11/2025",
    genres: [" Hài, Tâm Lý"],
    age_rating: "T13",
    language: "Việt Nam",
    subtitles: ["Việt", "Anh"],
    director: " Nguyễn Ngọc Lâm",
    status: "soon",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Việt Nam ", " Hài "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "20",
    title_vi: "CWICKED: PHẦN 2",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/w/f/wfg-470x700.jpg",
    trailer_url: "https://youtu.be/lZ4_nMbdlFQ",
    synopsis:
      "Bộ phim chuyển thể từ sân khấu Broadway thành công nhất mọi thời đại, hiện tượng điện ảnh toàn cầu năm 2024 nay chính thức đi đến hồi kết hoành tráng, kịch tính và đầy cảm xúc trong Wicked: Phần 2. Chương cuối của câu chuyện bắt đầu khi Elphaba và Glinda đã xa cách, mỗi người đang sống với hậu quả từ những lựa chọn của riêng mình. Elphaba giờ đây bị cả xứ Oz xem như Phù thủy độc ác phương Tây, trong khi đó Glinda đã trở thành biểu tượng quyến rũ của Lòng tốt đối với toàn bộ xứ Oz. Và mọi thứ thay đổi khi một cô gái đến từ Kansas bất ngờ xuất hiện, khiến cuộc sống của xứ Oz bị đảo lộn. Glinda và Elphaba buộc phải cùng nhau đối mặt lần cuối, họ phải thật sự thấu hiểu nhau, bằng sự trung thực và đồng cảm, nếu muốn thay đổi chính mình và cả vận mệnh của xứ Oz. Liệu Elphaba và Glinda có thể vượt qua số phận đã được định sẵn để viết lại tương lai cho xứ sở phép màu này?",
    duration_mins: 138,
    release_date: "21/11/2025",
    genres: [" Nhạc kịch, Thần thoại"],
    age_rating: "T13",
    language: "Mỹ",
    subtitles: ["Việt", "Anh"],
    director: " Jon M. Chu",
    status: "soon",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Việt Nam ", " Hài "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },
  {
    movie_id: "21",
    title_vi: "ANH TRAI SAY XE",
    title_en: "The Lost Dragon Incense",
    poster_url:
      "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/4/7/470wx700h-atsx.jpg",
    trailer_url: "https://youtu.be/7xpwkL54Cvs",
    synopsis:
      "Đã bao lâu bạn chưa du lịch cùng bạn thân?” Nhóm bạn nối khố của Tae Jeong, Do Jin, Yeon Min và Geum Bok đã ấp ủ một chuyến du lịch cùng nhau ngay sau khi tốt nghiệp cấp III, thế nhưng rốt cuộc vì thế này thế kia mà cả bọn đã lỡ hẹn. Hơn mười năm sau, người phải “bán mình cho tư bản”, người thì xuất gia, người đi định cư, có người lại mắc cả bệnh tâm lý. Nhưng nhóm “bốn thằng cốt” vẫn quyết định cùng nhau thực hiện lời hứa chuyến xuất ngoại đầu tiên. Bốn “anh trai say xe” này đã quậy tưng Bangkok, biến “chuyến đi đầu tiên” thành một kỉ niệm nhớ đời với vô vàn kịch tính lẫn tiếng cười, nước mắt. Nhất là khi, cô nàng vô duyên Ok Sim còn bám riết như kỳ đà!? Lần đầu tiên trên màn ảnh rộng, hai tài tử Kang Ha Neul và Cha Eun Woo bắt tay nhau tạo nên những thước phim thanh xuân mãn nhãn và đẩy cảm xúc.",
    duration_mins: 138,
    release_date: "21/11/2025",
    genres: [" Hài"],
    age_rating: "T13",
    language: "Hàn",
    subtitles: ["Việt", "Anh"],
    director: " Nam Dae Jung",
    status: "soon",
    cast: [
      { actor_name: " Glen Powell", role: "Tâm" },
      { actor_name: "William H", role: "Tuấn" },
      { actor_name: "HLee Pace", role: "Bạn Tâm" },
      { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
    ],
    rating: 8.5,
    format: ["2D", "2D Phụ đề"],
    price: 50000,
    tags: ["Hot", "Việt Nam ", " Hài "],
    is_showing: true,
    is_coming_soon: false,
    seat_map_id: "seats_1",
    cinemas: [
      {
        cinema_name: "Cinema center",
        showtimes: {
          "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
          "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
          "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
          "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
        },
      },
    ],
    reviews: [
      {
        user: "Fan Godzilla",
        rating: 0,
        date: "2025-11-20",
        comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
      },
      {
        user: "Người nghiện IMAX",
        rating: 0,
        date: "2025-11-20",
        comment:
          "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
      },
    ],
  },

//    {
//     movie_id: "22",
//     title_vi: "Hoàng Tử Quỷ",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://cdn.moveek.com/storage/media/cache/short/69097332332be460386107.jpg",
//     trailer_url: "https://youtu.be/NieKQnVIk0Q",
//     synopsis:
//       "Hoàng Tử Quỷ xoay quanh Thân Đức - một hoàng tử được sinh ra nhờ tà thuật. Trốn thoát khỏi cung cấm, Thân Đức tham vọng giải thoát Quỷ Xương Cuồng khỏi Ải Mắt Người để khôi phục Xương Cuồng Giáo. Nhưng kế hoạch của Thân Đức chỉ thành hiện thực khi hắn có đủ cả hai “nguyên liệu” - Du Hồn Giả và Bạch Hổ Nguyên Âm. Đội lốt một lang y hiền lành, muốn chữa bệnh cứu người, Thân Đức lên đường đến làng Hủi và đụng độ trưởng làng Lỗ Đạt mạnh mẽ, liệu hắn có thể đạt được âm mưu tà ác của mình?” thành một kỉ niệm nhớ đời với vô vàn kịch tính lẫn tiếng cười, nước mắt. Nhất là khi, cô nàng vô duyên Ok Sim còn bám riết như kỳ đà!? Lần đầu tiên trên màn ảnh rộng, hai tài tử Kang Ha Neul và Cha Eun Woo bắt tay nhau tạo nên những thước phim thanh xuân mãn nhãn và đẩy cảm xúc.",
//     duration_mins: 117,
//     release_date: "05/12/2025",
//     genres: ["Kinh dị"],
//     age_rating: "T18",
//     language: "Việt Nam",
//     subtitles: ["Việt", "Anh"],
//     director: " Trần Hữu Tấn",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Kinh dị "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//  {
//     movie_id: "23",
//     title_vi: "Anh Trai Tôi Là Khủng Long: Tương Lai Của Quá Khứ",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://files.betacorp.vn/media%2fimages%2f2025%2f12%2f04%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D12%2D04%2D112314%2D112426%2D041225%2D65.png",
//     trailer_url: "https://youtu.be/DIA42ZN2mxY",
//     synopsis:
//       " đẩy cảm xúc.Tưởng rằng ác quỷ đã bị diệt trừ, nhưng hắn đã trở lại — mạnh mẽ hơn, tàn nhẫn hơn. Khi thực tại sụp đổ, Phong và Nghi buộc phải bước vào hành trình ngược dòng thời gian, trở về thời khắc trước khi thảm họa bắt đầu. Giữa ranh giới của niềm tin và tuyệt vọng, họ chỉ có một cơ hội để thay đổi số phận loài người… dù phải đánh đổi chính sự tồn tại của mình. Kiếp nạn vượt thời gian của Phong và Nghi. Tương lai nào cho quá khứ? Phim điện ảnh Anh Trai Tôi Là Khủng Long sắp tới rồi, sắp tới rồi!",
//     duration_mins: 95 ,
//     release_date: "12/12/2025",
//     genres: ["Hoạt hình, Thần thoại"],
//     age_rating: "T13",
//     language: "Hàn",
//     subtitles: ["Việt", "Anh"],
//     director: " Nam Dae Jung",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
// {
//     movie_id: "24",
//     title_vi: "5 Centimet Trên Giây",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://files.betacorp.vn/media%2fimages%2f2025%2f11%2f24%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D11%2D24%2D172452%2D172554%2D241125%2D91.png",
//     trailer_url: "https://youtu.be/eZsMunqo09I",
//     synopsis:
//       "Câu chuyện cảm động về Takaki và Akari, đôi bạn thuở thiếu thời dần bị chia cắt bởi thời gian và khoảng cách. Qua ba giai đoạn khác nhau trong cuộc đời, hành trình khắc họa những ký ức, cuộc hội ngộ và sự xa cách của cặp đôi, với hình ảnh hoa anh đào rơi – 5cm/giây – như ẩn dụ cho tình yêu mong manh và thoáng chốc của tuổi trẻ.",
//     duration_mins:76 ,
//     release_date: "12/12/2025",
//     genres: ["Tình cảm, Hoạt hình"],
//     age_rating: "T13",
//     language: "Tiếng Nhật",
//     subtitles: ["Việt", "Anh"],
//     director: " Shinkai Makoto",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
// {
//     movie_id: "25",
//     title_vi: "Chú Thuật Hồi Chiến: Biến Cố Shibuya x Tử Diệt Hồi Du - The Movie",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://files.betacorp.vn/media%2fimages%2f2025%2f12%2f03%2f400x633%2D1%2D091605%2D031225%2D47.jpg",
//     trailer_url: "https://youtu.be/WWa59IPvN1c",
//     synopsis:
//       "Sau bao ngày chờ đợi, Đại Chiến Shibuya cuối cùng cũng xuất hiện trên màn ảnh rộng, gom trọn những khoảnh khắc nghẹt thở nhất thành một cú nổ đúng nghĩa. Không chỉ tái hiện toàn bộ cơn ác mộng tại Shibuya, bộ phim còn hé lộ những bí mật then chốt và mở màn cho trò chơi sinh tử “Tử Diệt Hồi Du” đầy kịch tính và mãn nhãn.",
//     duration_mins:88  ,
//     release_date: "05/12/2025",
//     genres: ["Hoạt hình, Hành động"],
//     age_rating: "T13",
//     language: "Tiếng Nhật",
//     subtitles: ["Việt", "Anh"],
//     director: " Shouta Goshozono",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
// {
//     movie_id: "26",
//     title_vi: "Nhà Hai Chủ",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://files.betacorp.vn/media%2fimages%2f2025%2f12%2f02%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D12%2D02%2D134935%2D135051%2D021225%2D86.png",
//     trailer_url: "https://youtu.be/DBJcGuXXVOE",
//     synopsis:
//       "Một gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:102  ,
//     release_date: "26/12/2025",
//     genres: ["Kinh dị"],
//     age_rating: "T18",
//     language: "Tiếng Việt",
//     subtitles: ["Việt", "Anh"],
//     director: "Trần Duy Linh & Phạm Trung Hiếu",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//   {
//     movie_id: "27",
//     title_vi: "Vua Của Các Vua",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://chieuphimquocgia.com.vn/_next/image?url=http%3A%2F%2Fapiv2.chieuphimquocgia.com.vn%2FContent%2FImages%2F0019503_0.jpg&w=256&q=75",
//     trailer_url: "https://youtu.be/wDT6jlmLimI",
//     synopsis:
//       "The King of Kings là phim hoạt hình Hàn Quốc kể về cuộc đời Chúa Giê-su. Bộ phim đã tạo nên kỷ lục doanh thu toàn cầu, được khán giả Bắc Mỹ yêu thích với điểm số gần như tuyệt đối. Tác phẩm nổi bật bởi hình ảnh tinh xảo và thông điệp về tình yêu, phép màu và lòng biết ơn. Tại Việt Nam, phim sẽ ra mắt toàn quốc vào mùa Giáng Sinh, từ 12/12/2025. gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:102  ,
//     release_date: "26/12/2025",
//     genres: ["Hoạt hình, Gia đình"],
//     age_rating: "T12",
//     language: "Tiếng Việt",
//     subtitles: ["Việt", "Anh"],
//     director: "Seong-ho Jang",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//    {
//     movie_id: "27",
//     title_vi: "Vua Của Các Vua",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "https://files.betacorp.vn/media%2fimhttps://youtu.be/wDT6jlmLimIages%2f2025%2f12%2f05%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D12%2D05%2D141106%2D141214%2D051225%2D30.png",
//     trailer_url: "https://youtu.be/wDT6jlmLimI",
//     synopsis:
//       "The King of Kings là phim hoạt hình Hàn Quốc kể về cuộc đời Chúa Giê-su. Bộ phim đã tạo nên kỷ lục doanh thu toàn cầu, được khán giả Bắc Mỹ yêu thích với điểm số gần như tuyệt đối. Tác phẩm nổi bật bởi hình ảnh tinh xảo và thông điệp về tình yêu, phép màu và lòng biết ơn. Tại Việt Nam, phim sẽ ra mắt toàn quốc vào mùa Giáng Sinh, từ 12/12/2025. gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:102  ,
//     release_date: "26/12/2025",
//     genres: ["Hoạt hình, Gia đình"],
//     age_rating: "T12",
//     language: "Tiếng Việt",
//     subtitles: ["Việt", "Anh"],
//     director: "Seong-ho Jang",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//    {
//     movie_id: "28",
//     title_vi: "Em Sẽ Khử Anh",
//     title_en: "The Lost Dragon Incense",
//     poster_url:
//       "htthttps://files.betacorp.vn/media%2fimages%2f2025%2f11%2f30%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D11%2D30%2D105303%2D110030%2D301125%2D67.pngps://files.betacorp.vn/media%2fimhttps://youtu.be/wDT6jlmLimIages%2f2025%2f12%2f05%2fanh%2Dchup%2Dman%2Dhinh%2D2025%2D12%2D05%2D141106%2D141214%2D051225%2D30.png",
//     trailer_url: "https://youtu.be/hKjb3p7j8M0",
//     synopsis:
//       " Một cặp đôi trẻ đầy tình yêu và hy vọng (Grace và Jackson) rời New York để chuyển đến ngôi nhà thừa kế tại vùng quê yên tĩnh. Giữa không gian cô lập, Grace vật lộn với chứng trầm cảm sau sinh và cố gắng tìm lại chính mình trong vai trò người mẹ. Nhưng khi cô dần rơi vào trạng thái rạn vỡ và hỗn loạn, đó không phải vì yếu đuối, mà chính nhờ trí tưởng tượng, nghị lực và sức sống mãnh liệt hoang dã, cô tìm thấy lại con người thật của mình.Kings là phim hoạt hình Hàn Quốc kể về cuộc đời Chúa Giê-su. Bộ phim đã tạo nên kỷ lục doanh thu toàn cầu, được khán giả Bắc Mỹ yêu thích với điểm số gần như tuyệt đối. Tác phẩm nổi bật bởi hình ảnh tinh xảo và thông điệp về tình yêu, phép màu và lòng biết ơn. Tại Việt Nam, phim sẽ ra mắt toàn quốc vào mùa Giáng Sinh, từ 12/12/2025. gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:118 ,
//     release_date: "12/12/2025",
//     genres: ["Giật gân, Hài hước"],
//     age_rating: "T12",
//     language: "Tiếng Anh",
//     subtitles: ["Việt", "Anh"],
//     director: "Seong-ho Jang",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//   {
//     movie_id: "29",
//     title_vi: "Thế Hệ Kỳ Tích (Bà Đừng Buồn Con)",
//     title_en: "The Lost Dragon Incense",
//     poster_url:"https://files.betacorp.vn/media%2fimages%2f2025%2f11%2f07%2fmain%2Dthkt%2Dcinema%2D171443%2D071125%2D38.png",
//     trailer_url: "https://youtu.be/09g3UYPsgNs",
//     synopsis:
//       " Chàng sinh viên Tiến (Trần Tú) mang trong mình giấc mơ tạo ra tựa game vươn tầm thế giới, dù liên tục bị xem thường và vấp ngã trên hành trình khởi nghiệp. Cùng với “thế hệ kỳ tích” – những người trẻ dám mơ và dám làm, Tiến từng bước khẳng định giá trị của bản thân. Giữa bao thử thách, tình yêu và niềm tin của người bà (NSND Thanh Hoa) chính là ngọn lửa giúp anh đứng dậy, biến ước mơ thành kỳ tích.Một cặp đôi trẻ đầy tình yêu và hy vọng (Grace và Jackson) rời New York để chuyển đến ngôi nhà thừa kế tại vùng quê yên tĩnh. Giữa không gian cô lập, Grace vật lộn với chứng trầm cảm sau sinh và cố gắng tìm lại chính mình trong vai trò người mẹ. Nhưng khi cô dần rơi vào trạng thái rạn vỡ và hỗn loạn, đó không phải vì yếu đuối, mà chính nhờ trí tưởng tượng, nghị lực và sức sống mãnh liệt hoang dã, cô tìm thấy lại con người thật của mình.Kings là phim hoạt hình Hàn Quốc kể về cuộc đời Chúa Giê-su. Bộ phim đã tạo nên kỷ lục doanh thu toàn cầu, được khán giả Bắc Mỹ yêu thích với điểm số gần như tuyệt đối. Tác phẩm nổi bật bởi hình ảnh tinh xảo và thông điệp về tình yêu, phép màu và lòng biết ơn. Tại Việt Nam, phim sẽ ra mắt toàn quốc vào mùa Giáng Sinh, từ 12/12/2025. gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:124 ,
//     release_date: "12/12/2025",
//     genres: ["Gia đình, Tâm lý"],
//     age_rating: "T12",
//     language: "Tiếng Anh",
//     subtitles: ["Việt", "Anh"],
//     director: "Hoàng Nam",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
//    {
//     movie_id: "30",
//     title_vi: "TAvatar: Lửa Và Tro Tàn",
//     title_en: "The Lost Dragon Incense",
//     poster_url:"https://files.betacorp.vn/media%2fimages%2f2025%2f12%2f11%2fbeta%2D400x633%2D111016%2D111225%2D97.png",
//     trailer_url: "https://youtu.be/erhF0RAnYvo",
//     synopsis:
//       " Sau nỗi đau khi mất đi đứa con trưởng, gia đình Jake Sully và Neytiri tiếp tục bị cuốn vào biến cố mới khi kẻ thù không đội trời chung Quaritch bắt tay với Varang - thủ lĩnh tộc Tro. Lần đầu trong suốt nhiều năm, đạo diễn James Cameron hé lộ mặt tối của người Na’vi, mang đến những góc khuất của Pandora mà khán giả chưa từng thấy trong Avatar: Lửa Và Tro Tàn. sinh viên Tiến (Trần Tú) mang trong mình giấc mơ tạo ra tựa game vươn tầm thế giới, dù liên tục bị xem thường và vấp ngã trên hành trình khởi nghiệp. Cùng với “thế hệ kỳ tích” – những người trẻ dám mơ và dám làm, Tiến từng bước khẳng định giá trị của bản thân. Giữa bao thử thách, tình yêu và niềm tin của người bà (NSND Thanh Hoa) chính là ngọn lửa giúp anh đứng dậy, biến ước mơ thành kỳ tích.Một cặp đôi trẻ đầy tình yêu và hy vọng (Grace và Jackson) rời New York để chuyển đến ngôi nhà thừa kế tại vùng quê yên tĩnh. Giữa không gian cô lập, Grace vật lộn với chứng trầm cảm sau sinh và cố gắng tìm lại chính mình trong vai trò người mẹ. Nhưng khi cô dần rơi vào trạng thái rạn vỡ và hỗn loạn, đó không phải vì yếu đuối, mà chính nhờ trí tưởng tượng, nghị lực và sức sống mãnh liệt hoang dã, cô tìm thấy lại con người thật của mình.Kings là phim hoạt hình Hàn Quốc kể về cuộc đời Chúa Giê-su. Bộ phim đã tạo nên kỷ lục doanh thu toàn cầu, được khán giả Bắc Mỹ yêu thích với điểm số gần như tuyệt đối. Tác phẩm nổi bật bởi hình ảnh tinh xảo và thông điệp về tình yêu, phép màu và lòng biết ơn. Tại Việt Nam, phim sẽ ra mắt toàn quốc vào mùa Giáng Sinh, từ 12/12/2025. gia đình nhỏ vì không đủ điều kiện đã phải mua một căn nhà mà người dân xung quanh đồn đoán rằng có nhiều điều kỳ lạ tâm linh liệu gia đình sẽ đối mặt với ngôi nhà nhiều chủ sẽ như thế nào?",
//     duration_mins:197 ,
//     release_date: "19/12/2025",
//     genres: ["Khoa học, viễn tưởng"],
//     age_rating: "T12",
//     language: "Tiếng Anh",
//     subtitles: ["Việt", "Anh"],
//     director: "James Cameron",
//     status: "soon",
//     cast: [
//       { actor_name: " Glen Powell", role: "Tâm" },
//       { actor_name: "William H", role: "Tuấn" },
//       { actor_name: "HLee Pace", role: "Bạn Tâm" },
//       { actor_name: "Michael Cerao", role: "Bạn gái Tuấn" },
//     ],
//     rating: 8.5,
//     format: ["2D", "2D Phụ đề"],
//     price: 50000,
//     tags: ["Hot", "Việt Nam ", " Hài "],
//     is_showing: true,
//     is_coming_soon: false,
//     seat_map_id: "seats_1",
//     cinemas: [
//       {
//         cinema_name: "Cinema center",
//         showtimes: {
//           "2025-11-22": ["11:00", "14:00", "17:00", "20:00", "23:00"],
//           "2025-11-23": ["10:30", "13:30", "16:30", "19:30", "22:30"],
//           "2025-11-24": ["12:00", "15:00", "18:00", "21:00"],
//           "2025-11-25": ["11:30", "14:30", "17:30", "20:30"],
//         },
//       },
//     ],
//     reviews: [
//       {
//         user: "Fan Godzilla",
//         rating: 0,
//         date: "2025-11-20",
//         comment: "Nhìn CGI trong trailer là biết rạp sẽ rung luôn!",
//       },
//       {
//         user: "Người nghiện IMAX",
//         rating: 0,
//         date: "2025-11-20",
//         comment:
//           "Chuẩn bị tinh thần cho cảnh Godzilla phun tia cực sexy trên màn IMAX.",
//       },
//     ],
//   },
]

export default DataMovie;